import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

import {
  poppins,
  poppinsBold,
  poppinsMedium,
  poppinsSemiBold,
} from '@/lib/fonts';

import CheckLogin from './middleware/checkLogin';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${poppins.variable} ${poppinsMedium.variable} ${poppinsSemiBold.variable} ${poppinsBold.variable}`}
      >
        <CheckLogin>{children}</CheckLogin>
        <ToastContainer autoClose={2000} />
      </body>
    </html>
  );
}
